# Generated by Django 2.2.4 on 2019-10-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombrepro', models.CharField(max_length=200, verbose_name='Nombre')),
                ('tipopro', models.CharField(max_length=200, verbose_name='Tipo')),
                ('colorpro', models.CharField(max_length=100, verbose_name='Color')),
                ('stock', models.IntegerField(verbose_name='Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('producto', models.ManyToManyField(to='api.Productos')),
            ],
        ),
    ]
